# Generated by Django 4.1 on 2022-08-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': '用户校验表', 'verbose_name_plural': '用户校验表'},
        ),
        migrations.RemoveField(
            model_name='oauthuser',
            name='last_mod_time',
        ),
    ]
