# Generated by Django 4.1 on 2022-09-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_oauthuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthuser',
            name='login_time',
        ),
    ]
