# Generated by Django 4.1 on 2022-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterModelTable(
            name='bloguser',
            table='user',
        ),
    ]
