# Generated by Django 4.1 on 2022-09-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_bloguser_email_alter_bloguser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='last_mod_time',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
