# Generated by Django 4.1 on 2022-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_bloguser_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': '手机号格式不正确'}, help_text='仅限11位数字', max_length=11, verbose_name='phone'),
        ),
    ]
