# Generated by Django 4.1 on 2022-09-10 15:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_bloguser_phone_bloguser_idcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(error_messages={'unique': '用户名已存在.'}, help_text='支持 16个字符，汉字、数字、字母以及特殊符号(@/./+/-/_)。', max_length=16, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
