# Generated by Django 4.1 on 2022-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_bloguser_idcard_alter_bloguser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='photo',
            field=models.ImageField(blank=True, height_field=150, upload_to='', verbose_name='photo', width_field=100),
        ),
    ]
