# Generated by Django 4.1 on 2022-09-10 16:04

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_bloguser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='idcard',
            field=models.CharField(blank=True, error_messages={'unique': '身份证格式不正确'}, max_length=18, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='idcard'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='name'),
        ),
    ]
