# Generated by Django 4.1 on 2022-09-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_bloguser_idcard_alter_bloguser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'ordering': ['-id'], 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
    ]
