# Generated by Django 4.1 on 2022-09-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='like',
            field=models.IntegerField(null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='pageviews',
            field=models.IntegerField(null=True, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='tags',
            field=models.JSONField(default='1', verbose_name='标签'),
            preserve_default=False,
        ),
    ]
