# Generated by Django 4.1 on 2022-09-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleinfo_like_articleinfo_pageviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='like',
            field=models.IntegerField(blank=True, default='1', verbose_name='点赞数'),
            preserve_default=False,
        ),
    ]
