# Generated by Django 4.1 on 2022-09-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articleinfo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='pageviews',
            field=models.IntegerField(blank=True, default=1, verbose_name='阅读量'),
            preserve_default=False,
        ),
    ]
