# Generated by Django 4.1 on 2022-09-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articleinfo_pageviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleinfo',
            options={'ordering': ['-article_id']},
        ),
    ]
